// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBAuiEV1daDgeFviH_4QOnTrR0Kjp9grc',
    appId: '1:670324928036:web:45410b5f8d51646d1d32b1',
    messagingSenderId: '670324928036',
    projectId: 'novev5',
    authDomain: 'novev5.firebaseapp.com',
    storageBucket: 'novev5.firebasestorage.app',
    measurementId: 'G-1ST5LGMH7K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMduEQ0J0-7qkAjRRuD2FhHqD6ESr74Q0',
    appId: '1:670324928036:android:b86c8d65b573c67a1d32b1',
    messagingSenderId: '670324928036',
    projectId: 'novev5',
    storageBucket: 'novev5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMtP0ncDcwJdFDZZA1CBqT0wk33KQFYSU',
    appId: '1:670324928036:ios:d3336e57b90c36651d32b1',
    messagingSenderId: '670324928036',
    projectId: 'novev5',
    storageBucket: 'novev5.firebasestorage.app',
    iosBundleId: 'com.example.nove5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMtP0ncDcwJdFDZZA1CBqT0wk33KQFYSU',
    appId: '1:670324928036:ios:d3336e57b90c36651d32b1',
    messagingSenderId: '670324928036',
    projectId: 'novev5',
    storageBucket: 'novev5.firebasestorage.app',
    iosBundleId: 'com.example.nove5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBAuiEV1daDgeFviH_4QOnTrR0Kjp9grc',
    appId: '1:670324928036:web:c7276a98c07e88421d32b1',
    messagingSenderId: '670324928036',
    projectId: 'novev5',
    authDomain: 'novev5.firebaseapp.com',
    storageBucket: 'novev5.firebasestorage.app',
    measurementId: 'G-4301DS606F',
  );
}
